### ISSUE TITLE
mochi-sdskv failing unit tests.

### ISSUE THREAD

**Issue by DonaldKruse** [mochi-hpc/mochi-sdskv#4]
The mochi-sdskv unit tests are failing on and after the put-test.sh test. The environment that these test were using is
```
Environment and loaded libraries:
==> In environment mochi
==> Root specs
mochi-sdskv   mochi-ssg   openmpi 
-- no arch / gcc@7.3.1 ------------------------------------------
mercury@master%gcc@7.3.1   mochi-margo@master%gcc@7.3.1 
==> 29 installed packages
-- linux-rhel7-power9le / gcc@7.3.1 -----------------------------
argobots@1.0         libiconv@1.16       openssl@1.0.2k
autoconf@2.69        libpciaccess@0.16   perl@5.32.1
automake@1.13.4      libsigsegv@2.12     pkg-config@0.29.2
berkeley-db@18.1.40  libxml2@2.9.10      rdma-core@20
gdbm@1.18.1          m4@1.4.18           readline@8.0
hwloc@2.4.0          mercury@master      snappy@1.1.8
json-c@0.13.1        mochi-abt-io@0.5    util-macros@1.19.1
leveldb@1.22         mochi-margo@master  xz@5.2.5
libevent@2.1.12      mochi-sdskv@0.1.9   zlib@1.2.11
libfabric@1.11.1     ncurses@6.2
```
and sdskv was built with `/prepare.sh; mkdir build; cd build; ../configure CXXFLAGS="-std=c++14"; make; make check`. The first part of the `test-suite.log` after running `make check` is 
```
FAIL: test/put-test.sh
======================

+ '[' -z .. ']'
+ source ../test/test-util.sh
++ '[' -z timeout ']'
++ '[' -z mktemp ']'
++ TMPDIR=/dev/shm
++ export TMPDIR
++ mkdir -p /dev/shm
+++ mktemp --tmpdir -d test-XXXXXX
++ TMPBASE=/dev/shm/test-1JfT03
++ '[' '!' -d /dev/shm/test-1JfT03 ']'
+ find_db_name
+ test_db_name=sdskv-test-db
+ test_db_type=map
+ test_db_full=/dev/shm/test-1JfT03/sdskv-test-db:map
+ test_start_server 2 20 /dev/shm/test-1JfT03/sdskv-test-db:map
+ startwait=2
+ maxtime=20
+ sleep 2
+ run_to 20 bin/sdskv-server-daemon -f /dev/shm/test-1JfT03/sdskv.addr na
+sm /dev/shm/test-1JfT03/sdskv-test-db:map
+ maxtime=20s
+ shift
+ timeout --signal=9 20s bin/sdskv-server-daemon -f /dev/shm/test-1JfT03/
sdskv.addr na+sm /dev/shm/test-1JfT03/sdskv-test-db:map
++ cat /dev/shm/test-1JfT03/sdskv.addr
+ svr_addr=na+sm://58282/0
+ sleep 3
+ run_to 20 test/sdskv-put-test na+sm://58282/0 1 sdskv-test-db 10
+ maxtime=20s
+ shift
+ timeout --signal=9 20s test/sdskv-put-test na+sm://58282/0 1 sdskv-test
-db 10
Error (sdskv_put_ult): could not find target database
Error: sdskv_put() failed (iteration 0, ret = 6)
no overwrite is 0
Provider 0 managing database "/dev/shm/test-1JfT03" at multiplex id 1
Successfuly open database sdskv-test-db, id is 80
+ '[' 255 -ne 0 ']'
+ wait
+ exit 1
```
Note that margo was verified to work by running the `margo-p2p-latency` test. Here is the full log: [test-suite.log](https://github.com/mochi-hpc/mochi-sdskv/files/6345909/test-suite.log)

How I reproduced this error using mochi-sdskv@master:

1. install and run via `/prepare.sh; mkdir build; cd build; ../configure CXXFLAGS="-std=c++14"; make; make check`.

**Comment by mdorier** [comment]
Thanks for reporting!

I wasn't able to reproduce the problem on my local machine. One thing that strikes me as odd is your version of Margo: master doesn't exist anymore since the migration to github (same for sdskv). Are you using the new Mochi package repository ([mochi-spack-packages](https://github.com/mochi-hpc/mochi-spack-packages))? Also it seems that spack has installed mochi-sdskv@0.1.9, which is an old version (the current one is mochi-sdskv@0.1.11), which hints again at your mochi package repository not being the correct one or not being up to date. Could you check that?

You can execute
```
spack repo list
```

Then go in the folder pointed by "mochi" and do
```
git remote -v
```
to check the repository (it should be https://github.com/mochi-hpc/mochi-spack-packages.git).
Thanks

**Comment by DonaldKruse** [comment]
So after a bit of fussing with spack. I think my environment is more-or-less up to date, since we are grabbing from main and not master (except mercury). 

Unfortunately we are still failing on put-check and onward.

My `spack find` output is
```
[kruse11@lassen708:build]$ spack find
==> In environment /g/g15/kruse11/Mochi
==> Root specs
argobots   mochi-sdskv@main +leveldb  mochi-ssg@main +mpi+pmix

-- no arch / gcc@7.3.1 ------------------------------------------
mercury@master%gcc@7.3.1   mochi-margo@main%gcc@7.3.1 

==> 43 installed packages
-- linux-rhel7-power9le / gcc@7.3.1 -----------------------------
argobots@1.1         gdbm@1.19         libfabric@1.11.1   mochi-abt-io@0.5.1    nlohmann-json@3.9.1  snappy@1.1.8                  zlib@1.2.11
autoconf@2.69        gettext@0.21      libiconv@1.16      mochi-bedrock@0.2     openssl@1.0.2k       spdlog@1.8.1
automake@1.13.4      help2man@1.47.16  libpciaccess@0.16  mochi-margo@main      perl@5.32.1          spectrum-mpi@rolling-release
berkeley-db@18.1.40  hwloc@2.4.1       libsigsegv@2.13    mochi-sdskv@main      pkg-config@0.29.2    tar@1.34
bzip2@1.0.8          json-c@0.15       libxml2@2.9.10     mochi-ssg@main        pmix@3.2.1           tclap@1.2.2
cereal@1.3.0         leveldb@1.22      m4@1.4.18          mochi-thallium@0.8.4  rdma-core@20         util-macros@1.19.1
diffutils@3.7        libevent@2.1.8    mercury@master     ncurses@6.2           readline@8.1         xz@5.2.5
```
Here is the full 
[config.log](https://github.com/mochi-hpc/mochi-sdskv/files/6353230/config.log)
and 
[test-suite.log](https://github.com/mochi-hpc/mochi-sdskv/files/6353232/test-suite.log)

**Comment by mdorier** [comment]
Thanks. Unfortunately even when trying to use the same versions as you, I couldn't reproduce the problem. What seems odd to me is this line from the log:
```
Successfuly open database sdskv-test-db, id is 80
```
The database id is the address of the corresponding database object in the memory of the server (it's effectively a pointer converted into a `uint64_t` value). 80 seems strange for a pointer value (that's typically not where the heap is!). The fact that the list-db test is successful and that the put test succeeds in opening the database (i.e. get an id from a name) seems to indicate that the server correctly creates a database and that the client can correctly query the server for it. But the returned id seems invalid. From there I see three possibilities:
- The server doesn't correctly compute and store the database id open creating the database;
- The server doesn't transfer correctly the database id (Mercury serialization error? something else?) to the client;
- The client does receive the correct database id but it is corrupted before being returned.

Ideally we would need some more logging in sdskv to trace exactly what happens, and that's something I have on my list, but it might take a few days before I can do that. If you want to track down the problem, since you are building sdskv from source already, you might want to look at those lines and add print statement to see what's happening:

- https://github.com/mochi-hpc/mochi-sdskv/blob/main/src/sdskv-server.cc#L397 here is where the database id is created when creating the database;
- https://github.com/mochi-hpc/mochi-sdskv/blob/main/src/sdskv-server.cc#L405 the three lines here store the database and the mapping from name to id and id to name;
- https://github.com/mochi-hpc/mochi-sdskv/blob/main/src/sdskv-server.cc#L563 this is where the database id is retrieved by the server when sdskv_open is called by the client;
- https://github.com/mochi-hpc/mochi-sdskv/blob/main/src/sdskv-client.c#L271 this is where the client gets the database id from the server in sdskv_open;

Adding print statements at those locations should help trace where the database id gets messed up.

**Comment by DonaldKruse** [comment]
We were able to get sdskv to pass the unit tests. I think that this was mainly do to my repo not being up to date.

**Comment by mdorier** [comment]
Ok thanks!
At any rate there will be a new release soon with more logging available, if you ever need.
